name: Docker Image CI

on:
  push:
    branches: [ test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ ORG_DOCKER_USER }}
        password: ${{ ORG_DOCKER_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with: 
        context: .
        push: true
        tags: artsdatabanken/responssjekk:test
            
